// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
.......71777........
.......71117........
.......ddddd........
.......dfdfd........
.......ddddd........
.......deeed........
.......ddddd........
.....777878777......
.....777878777......
.....778585877......
.....778888877......
.....778888877......
.....118888811......
.....118888811......
.......8...8........
.......8...8........
.......8...8........
.......e...e........
.......e...e........
.....eee...eee......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
